<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="BSC-PF10PQNE" name="koch.com.ixigo.verifyIxigo" tests="4" failures="1" timestamp="12 Sep 2020 07:05:10 GMT" time="63.640" errors="0">
  <testcase name="verifyNonStopFlights" time="0.000" classname="koch.com.ixigo.verifyIxigo">
    <skipped/>
  </testcase> <!-- verifyNonStopFlights -->
  <testcase name="verifyIxigoPageIsLoaded" time="8.711" classname="koch.com.ixigo.verifyIxigo"/>
  <testcase name="verifyFlightsWithFareLessThanFiveThosuand" time="0.000" classname="koch.com.ixigo.verifyIxigo">
    <skipped/>
  </testcase> <!-- verifyFlightsWithFareLessThanFiveThosuand -->
  <testcase name="verifyPassangerDetailsAreAdded" time="54.929" classname="koch.com.ixigo.verifyIxigo">
    <failure type="java.lang.AssertionError" message="Verify From Place Acutual : IXG - Belgaum Expected is : PNQ - Pune expected [PNQ - Pune] but found [IXG - Belgaum]">
      <![CDATA[java.lang.AssertionError: Verify From Place Acutual : IXG - Belgaum Expected is : PNQ - Pune expected [PNQ - Pune] but found [IXG - Belgaum]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at koch.com.ixigo.verifyIxigo.verifyPassangerDetailsAreAdded(verifyIxigo.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyPassangerDetailsAreAdded -->
</testsuite> <!-- koch.com.ixigo.verifyIxigo -->
